---
- hosts: all
  vars:
  - warName: webapp.war
  - tomcat_version: 10.1.8
  - warRemotePath: /root/maven-project/webapp/target/webapp.war

  tasks:
  - name: Copy WAR to Remote server
    copy: src=/root/maven-project/webapp/target/webapp.war  dest=/opt/apache-tomcat-10.1.8/webapps/simpli-project-0.0.1-SNAPSHOT.war  owner=tomcat group=tomcat

